### ISSUE TITLE
The parameter `start` for `sev::launch::sev::Launcher::start` should be passed by reference

### ISSUE THREAD

**Issue by FuuuOverclocking** [virtee/sev#82]
Since `Start` is a data structure that reaches up to 2KB in size (typically), I think it should be passed by reference.

i.e.
```rs
    pub fn start(mut self, start: Start) -> Result<Launcher<Started, U, V>> {
```
to
```rs
    pub fn start(mut self, start: &Start) -> Result<Launcher<Started, U, V>> {
```

**Comment by tylerfanelli** [comment]
@FuuuOverclocking Thanks for pointing this out. I think our initial motivation for passing by value is that we wanted the function to consume the value instead of allowing it to be re-used. I suppose there is no issue in letting it be re-used. However, I've never run into any issue with this API as is.

@larrydewey what do you think here? Obviously we'd like to avoid a situation in which a stack overflow could result.

**Comment by tylerfanelli** [comment]
Closing this for now, but will re-consider on `2.0.0` release, as this change breaks API.
